include: package:surf_lint_rules/analysis_options.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "bin/cache/**"
    - "dev/conductor/lib/proto/*"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "**/generated/**"

linter:
  rules:
    flutter_style_todos: false
    omit_local_variable_types: false
    sort_pub_dependencies: false

dart_code_metrics:
  metrics:
    technical-debt:
      threshold: 1
      todo-cost: 1
      ignore-cost: 1
      ignore-for-file-cost: 1
      as-dynamic-cost: 1
      deprecated-annotations-cost: 1
      file-nullsafety-migration-cost: 1
      unit-type: "CRAB HANDS"